<?php
/** @var Button $block */
/** @var Escaper $escaper */

use Abeta\PunchOut\Block\Cart\Button;
use Magento\Framework\Escaper;

$buttonText = $block->getButtonLabel();
?>

<?php if ($block->isNeedToShow()): ?>
    <?php if ($block->useModal()): ?>
        <div class="punch-out-button-wrapper"
             data-mage-init='{
             "Abeta_PunchOut/js/abeta-modal": {
                 "buttonLabel": "<?= $escaper->escapeHtml($buttonText); ?>"
              }
         }'>
            <button class="action primary punch-out"
                    id="punch-out-button"
                    type="button"
                    title="<?= $escaper->escapeHTML($buttonText); ?>">
                <?= $escaper->escapeHTML($buttonText); ?>
            </button>

            <div id="punch-out-button-modal" hidden>
                <div class="message hidden" id="punch-out-popup-message"><div></div></div>
                <table id="punch-out-table">
                    <thead>
                    <tr>
                        <th><?= $escaper->escapeHtml(__('Product name')) ?></th>
                        <th width="120px"><?= $escaper->escapeHtml(__('Qty')) ?></th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    <?php else: ?>
        <div class="punch-out-button-wrapper">
            <a href="<?= $escaper->escapeUrl($block->getPunchOutUrl()); ?>" class="action primary punch-out">
                <?= $escaper->escapeHTML($buttonText); ?>
            </a>
        </div>
    <?php endif; ?>
    <style>
        [data-role="proceed-to-checkout"] { display: none !important; }
    </style>
    <?php if ($customCss = $block->getCustomCss()): ?>
        <style>
            <?= $escaper->escapeHtml($customCss, ['noEscape' => true]); ?>
        </style>
    <?php endif; ?>
<?php endif; ?>
